server:
  port: 8891
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@10.2.25.123/ggrdattest
    username: greescmdb2
    password: passwd
shardingsphere:
  elasticjob:
    zk-config:
      serverLists: 10.2.30.38:32311
      namespace: my-job1
      baseSleepTimeMilliseconds: 3000
      maxSleepTimeMilliseconds: 4000
      maxRetries: 3
    trace-config:
      driverClass: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.2.30.38:3306/elastictrace?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: elastic
      password: Ela*Scm*123


