server:
  port: 8891
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/blog_db?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: hints0816
shardingsphere:
  elasticjob:
    zk-config:
      serverLists: 47.119.167.128:2181
      namespace: my-job1
      baseSleepTimeMilliseconds: 3000
      maxSleepTimeMilliseconds: 4000
      maxRetries: 3
    trace-config:
      driverClass: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog_db?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: hints0816


